Update bot.yml

diff --git a/.github/workflows/bot.yml b/.github/workflows/bot.yml
--- a/.github/workflows/bot.yml
+++ b/.github/workflows/bot.yml
@@ -25,13 +25,24 @@ jobs:
           wget http://prdownloads.sourceforge.net/ta-lib/ta-lib-0.4.0-src.tar.gz
           tar -xzf ta-lib-0.4.0-src.tar.gz
           cd ta-lib/
-          ./configure --prefix=/usr
+          ./configure --prefix=/usr/local
           make
           sudo make install
           cd ..
           sudo ldconfig
+          ls -l /usr/local/lib | grep ta_lib
+
+      - name: Verify TA-Lib Library
+        run: |
+          if [ ! -f /usr/local/lib/libta_lib.so ]; then
+            echo "TA-Lib library not found in /usr/local/lib!"
+            ls -l /usr/local/lib
+            exit 1
+          fi
 
       - name: Install dependencies
+        env:
+          LD_LIBRARY_PATH: /usr/local/lib
         run: |
           python -m pip install --upgrade pip
           pip install --no-cache-dir ta-lib
@@ -70,13 +81,24 @@ jobs:
           wget http://prdownloads.sourceforge.net/ta-lib/ta-lib-0.4.0-src.tar.gz
           tar -xzf ta-lib-0.4.0-src.tar.gz
           cd ta-lib/
-          ./configure --prefix=/usr
+          ./configure --prefix=/usr/local
           make
           sudo make install
           cd ..
           sudo ldconfig
+          ls -l /usr/local/lib | grep ta_lib
+
+      - name: Verify TA-Lib Library
+        run: |
+          if [ ! -f /usr/local/lib/libta_lib.so ]; then
+            echo "TA-Lib library not found in /usr/local/lib!"
+            ls -l /usr/local/lib
+            exit 1
+          fi
 
       - name: Install dependencies
+        env:
+          LD_LIBRARY_PATH: /usr/local/lib
         run: |
           python -m pip install --upgrade pip
           pip install --no-cache-dir ta-lib
@@ -114,11 +136,20 @@ jobs:
           wget http://prdownloads.sourceforge.net/ta-lib/ta-lib-0.4.0-src.tar.gz
           tar -xzf ta-lib-0.4.0-src.tar.gz
           cd ta-lib/
-          ./configure --prefix=/usr
+          ./configure --prefix=/usr/local
           make
           sudo make install
           cd ..
           sudo ldconfig
+          ls -l /usr/local/lib | grep ta_lib
+
+      - name: Verify TA-Lib Library
+        run: |
+          if [ ! -f /usr/local/lib/libta_lib.so ]; then
+            echo "TA-Lib library not found in /usr/local/lib!"
+            ls -l /usr/local/lib
+            exit 1
+          fi
 
       - name: Download Analyzer DB
         uses: actions/download-artifact@v4
@@ -131,6 +162,8 @@ jobs:
           name: signals-json
 
       - name: Install dependencies
+        env:
+          LD_LIBRARY_PATH: /usr/local/lib
         run: |
           python -m pip install --upgrade pip
           pip install --no-cache-dir ta-lib
